//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Prin_01 {
            get {
                object obj = ResourceManager.GetObject("Prin_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_02 {
            get {
                object obj = ResourceManager.GetObject("Prin_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_03 {
            get {
                object obj = ResourceManager.GetObject("Prin_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_04 {
            get {
                object obj = ResourceManager.GetObject("Prin_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_05 {
            get {
                object obj = ResourceManager.GetObject("Prin_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_06 {
            get {
                object obj = ResourceManager.GetObject("Prin_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_07 {
            get {
                object obj = ResourceManager.GetObject("Prin_07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_08 {
            get {
                object obj = ResourceManager.GetObject("Prin_08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_09 {
            get {
                object obj = ResourceManager.GetObject("Prin_09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_10 {
            get {
                object obj = ResourceManager.GetObject("Prin_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_11 {
            get {
                object obj = ResourceManager.GetObject("Prin_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_12 {
            get {
                object obj = ResourceManager.GetObject("Prin_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_13 {
            get {
                object obj = ResourceManager.GetObject("Prin_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_14 {
            get {
                object obj = ResourceManager.GetObject("Prin_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_15 {
            get {
                object obj = ResourceManager.GetObject("Prin_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_16 {
            get {
                object obj = ResourceManager.GetObject("Prin_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_17 {
            get {
                object obj = ResourceManager.GetObject("Prin_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_18 {
            get {
                object obj = ResourceManager.GetObject("Prin_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_19 {
            get {
                object obj = ResourceManager.GetObject("Prin_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_20 {
            get {
                object obj = ResourceManager.GetObject("Prin_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_21 {
            get {
                object obj = ResourceManager.GetObject("Prin_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_22 {
            get {
                object obj = ResourceManager.GetObject("Prin_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_23 {
            get {
                object obj = ResourceManager.GetObject("Prin_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_24 {
            get {
                object obj = ResourceManager.GetObject("Prin_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_25 {
            get {
                object obj = ResourceManager.GetObject("Prin_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_26 {
            get {
                object obj = ResourceManager.GetObject("Prin_26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_27 {
            get {
                object obj = ResourceManager.GetObject("Prin_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_28 {
            get {
                object obj = ResourceManager.GetObject("Prin_28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_29 {
            get {
                object obj = ResourceManager.GetObject("Prin_29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_30 {
            get {
                object obj = ResourceManager.GetObject("Prin_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_31 {
            get {
                object obj = ResourceManager.GetObject("Prin_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_32 {
            get {
                object obj = ResourceManager.GetObject("Prin_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_33 {
            get {
                object obj = ResourceManager.GetObject("Prin_33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_34 {
            get {
                object obj = ResourceManager.GetObject("Prin_34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_35 {
            get {
                object obj = ResourceManager.GetObject("Prin_35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_36 {
            get {
                object obj = ResourceManager.GetObject("Prin_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_37 {
            get {
                object obj = ResourceManager.GetObject("Prin_37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_38 {
            get {
                object obj = ResourceManager.GetObject("Prin_38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_39 {
            get {
                object obj = ResourceManager.GetObject("Prin_39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_40 {
            get {
                object obj = ResourceManager.GetObject("Prin_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_41 {
            get {
                object obj = ResourceManager.GetObject("Prin_41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_42 {
            get {
                object obj = ResourceManager.GetObject("Prin_42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_43 {
            get {
                object obj = ResourceManager.GetObject("Prin_43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_44 {
            get {
                object obj = ResourceManager.GetObject("Prin_44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_45 {
            get {
                object obj = ResourceManager.GetObject("Prin_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_46 {
            get {
                object obj = ResourceManager.GetObject("Prin_46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_47 {
            get {
                object obj = ResourceManager.GetObject("Prin_47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Prin_48 {
            get {
                object obj = ResourceManager.GetObject("Prin_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
